### PR TITLE
Fix #351, Fix #355 - Preserve legacy external storage

### LINKED ISSUE #351: Beta users have file access problems on API30+
Users reported, that they can't see any file (e.g. map files or cartridges) unless they have been downloaded by WhereYouGo.

I stumbled upon this line in AndroidManifest.xml:
https://github.com/cgeo/WhereYouGo/blob/35b4fe547a464d42a095f9fcb8abbd19fadc7792/src/main/AndroidManifest.xml#L36

I think we need to use `android:preserveLegacyExternalStorage="true"` instead to keep the loophole open, like we do in c:geo:
https://github.com/cgeo/cgeo/blob/24dd6766b0c713cffed3ade8feb66b4a755bd270/main/AndroidManifest.xml#L56

@eddiemuc 
Do you remember the difference between both?

### LINKED ISSUE #355: Raise the compileSDK to 30
Seems we need to raise the compileSDK to 30 as well to make it build.

@eddiemuc or others:
Any idea whether this could lead to behavior changes?

_Originally posted by @Lineflyer in https://github.com/cgeo/WhereYouGo/issues/354#issuecomment-1007996564_

### PR DESCRIPTION
**Pull request by Lineflyer**
## Description

Set the flag to preserve the legacy external storage to at least help users, who upgrade the app.

Note:
On new installations this has no effect. Need scoped storage to re-enable file access

## Related issues

#351
Related to #309

### CODE REVIEW

**Comment by Lineflyer** [comment]
Seems we need to raise the compileSDK to 30 as well to make it build.

@eddiemuc or others:
Any idea whether this could lead to behavior changes?

**Comment by eddiemuc** [comment]
> Seems we need to raise the compileSDK to 30 as well to make it build.
> 
> @eddiemuc or others: Any idea whether this could lead to behavior changes?

since the preserve-flag only has an effect if compileSDK is 30, the coupling to compilation makes sense :-)

I only ever dealt with SAF, I guess it is clear how this affects the app (you described it correctly in this PRs text). I don't know what else got introduced with SDK 30.

**Comment by eddiemuc** [comment]
For the effects on WhereYouGo see my comment on #351. I would advise NOT to put out a release of WhereYouGo with SDk30/perserve=true unless it already contains migration to SAF

**Comment by Lineflyer** [comment]
>  I would advise NOT to put out a release of WhereYouGo with SDk30/perserve=true unless it already contains migration to SAF

But if we put a version out without preserve flag while on target API=30 the file access will be gone anyway and not being able to migrate things even if we set the flag lateron... Or am I missing something here?

**Comment by eddiemuc** [comment]
> >  I would advise NOT to put out a release of WhereYouGo with SDk30/perserve=true unless it already contains migration to SAF
> 
> But if we put a version out without preserve flag while on target API=30 the file access will be gone anyway and not being able to migrate things even if we set the flag lateron... Or am I missing something here?

That's true. Hm. I guess we don't have a chance then

**Comment by Lineflyer** [comment]
> That's true. Hm. I guess we don't have a chance then

There is no big migration needed for WhereYouGo... it only reads/writes cartridges and reads maps.
As long as new users stick to default folders cartridge reading/writing is no problem, mapfile though do not work.

But thats the best we can do right now without letting users wait rather long (and non functional on Android 12 due to GPS problem).

**Pull request merged**
