### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a link to get your app on F-Droid 👍

### CODE REVIEW

**Comment by rsudev** [comment]
Ok to test

**Review by bekuno — CHANGES_REQUESTED** [review]
Please move your text to the end of the README. The following pragraph refers to the Google Play preparation.

**Comment by Lineflyer** [comment]
> Please move your text to the end of the README. The following pragraph refers to the Google Play preparation.

Its already placed where you requested, isn't it?

**Review by Lineflyer — APPROVED** [review]

**Comment by bekuno** [comment]
> Please move your text to the end of the README. The following pragraph refers to the Google Play preparation.
> 
> Its already placed where you requested, isn't it?

No.
The new text is currently inserted before the last paragraph.

**Comment by Poussinou** [comment]
Done

**Review by bekuno — APPROVED** [review]

**Comment by bekuno** [comment]
@Poussinou 
Many thanks for your contribution.

**Pull request merged**
