### PR TITLE
next release

### PR DESCRIPTION
**Pull request by bekuno**
- increase version number
- update descriptions
- remove changelog cs, wrote changelog en + de
- update README

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by kumy** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@kumy Great work  :-)
And the PR apk is fine.

**Comment by kumy** [comment]
Let's try renaming the apk with current PR id

retest this please

**Comment by kumy** [comment]
again, including date and commit id
retest this please

**Comment by bekuno** [comment]
> again, including date and commit id
Good idea.

**Comment by bekuno** [comment]
Then let's try this PR as our first nightly.

**Comment by hakuchi** [comment]
should there not also be increased the `versionCode` to make it possible to update the app without uninstalling preious version?

**Comment by kumy** [comment]
It's mostly again a problem of signature. This build was signed using the cgeo key, not the official whereyougo key.

@mucek4 could you give me a hint on where to find the whereyougo signing key please?

**Pull request merged**
