### PR TITLE
define in app used translations

### LINKED ISSUE #126: define in app used translations
Our inofficial rule in c:geo is to only add new languages if they have ~50% or more translated. (see https://github.com/cgeo/cgeo/pull/8023). This seems a idea to not too much mix few native translations with mostly English.
But with the crowdin integration currently all defined languages are transferred, also the new languages with 0% approved: Slovenian, Svedish, Turkish  
Can we limit the exchange from/to crowdin in the yaml file?
Or is the definition as in c:geo within main/build.gradle:
~~~
android {
    defaultConfig {
        // include only those language resources from libraries which we actively maintain ourself in the translation project
        resConfigs "en","ca","ceb","cs","da","de","el","es","fi","fr","hu","it","ja","ko","lt",...
~~~
a usefull solution?

edit:
for the second solution see https://developer.android.com/studio/build/shrink-code#unused-alt-resources

### PR DESCRIPTION
**Pull request by bekuno**
fixes #126

Define supported languages based on a fixed list.
This reduces the string resources in the apk to only these languages.
As additional point we need no extra handling for the crowdin export on not yet ready for use languages.

### CODE REVIEW

**Comment by bekuno** [comment]
Result:
whereyougo 0.9.3: 496 string ressources acrross 38 configurations
now:                      519 string ressources acrross 23 configurations

**Comment by Lineflyer** [comment]
BTW: I removed some of the "empty" languages on Crowdin meanwhile. You might want to reenable this if you like.

**Comment by bekuno** [comment]
> 
> 
> BTW: I removed some of the "empty" languages on Crowdin meanwhile. You might want to reenable this if you like.

For now I adjusted the PR for the current languages at crowdin.
Is there a standard procedure if someone wants to translate a new language?

**Comment by Lineflyer** [comment]
Just today a native turkish asked my to enable turkish again...sorry. I enabled it again, but for sure it will need time until we have sufficient translation.
No need to reinstantiate the files...I guess crowdin will push them back again next push event.

N

**Comment by Lineflyer** [comment]
you still have the deletion of the turkish files in here. Maybe you should start over in another PR with just the gradle changes.

**Comment by bekuno** [comment]
yes, I planned to push this before the languages import ...

**Pull request merged**
