### PR TITLE
detect and insert requestVerificationToken (fix #412)

### LINKED ISSUE #412: Fail to download cartridge
### Describe your problem!

The current WhereYouGo version stopped downloading cartridges even with successful login.
This means, that on newer Android devices there is no possibility to use WhereYouGo to play cartridges, because
1. using a user-accesible dir for manual providing cartridges is not yet supported (no SAF)
2. download no longer working

I did not look into why its failing but there are user reports and I can reproduce, that cartridges are not loaded "Lädt herunter: Fehler".

### How to reproduce?

Try to download a cartridge in WhereYouGo (e.g. triggered by c:geo).

### Actual result after these steps?

It fails

### Expected result after these steps?

it should download the cartridge

### Reproducible

Yes

### WhereYouGo Version

2022.01.14

### System information

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by moving-bits**
## Description
Whereigo pages require a "requestVerificationToken" on subsequent forms to be able to deliver the cartridge

### CODE REVIEW

**Comment by bekuno** [comment]
DNM - the gradle update needs an additional step.
I will prepare a PR and a TODO. Then you can decide to use the PR or to do it in this PR.

**Comment by moving-bits** [comment]
Thanks for looking into it. Feel free to add a commit to this PR (or create a separate PR, if you prefer).

I needed to upgrade Gradle, as WYG did not install for me with the old configuration, neither in emulator nor on physical device. After upgrading Gradle and plugin, everything was smooth.

**Comment by bekuno** [comment]
I created PR #417, it was alredy in the pipeline.

**Comment by moving-bits** [comment]
@bekuno 
Thanks. So we should merge #417 first, then this PR? Or anything that needs to be done in between?

**Comment by bekuno** [comment]
>  Thanks. So we should merge #417 first, then this PR? Or anything that needs to be done in between?

Yes, first merge #417.
The AGP update brings some configuration changes, but they can also be done afterwards.

**Pull request merged**
