### PR TITLE
Start Map with OSM (fix #74)

### LINKED ISSUE #74: Don't start with empty map
**Describe the bug:**
After installation of WhereYouGo and selecting "Map" from the main menu the user only sees an empty map.

**To Reproduce:**
1. Install WhereYouGo and start it
2. Select "Map" from the main menu

**Actual behavior/state after performing these steps:**
You will see an empty map screen and have to manually select the map source (once, then saved) to finally see the map.

**Expected behavior/state after performing these steps:**
For a good user experience we should set a default online map source.

**Version of WhereYouGo used:**
2020.03.08

**Is the problem reproducible:**
Yes

### PR DESCRIPTION
**Pull request by jakedot**
A shot in the dark, but I think this time it's really not more complicated than that.

Attempts to fix #74

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

**Comment by jakedot** [comment]
it leaves an error.log. Looks like that was not the change I should have been looking for.

NullPointerException in 
java.lang.String.replace()
menion.android.whereyougo.preferences.PreviewListPreference.getSummary():32

I think I will have to finally install AS

**Comment by jakedot** [comment]
retest this please

**Comment by jakedot** [comment]
looks good to me now :)

**Comment by jakedot** [comment]
squashed commits

**Comment by jakedot** [comment]
@Lineflyer did I make a mistake by using master as the base branch? Otherwise this PR is finished I think.

**Comment by Lineflyer** [comment]
Yes, ideally this can go to `release´ as it is a bug fix.
Please rebase to release (which in fact should be no difference as branches are equal at this moment).
So it should work to just open a PR towards release with the same commit.

**Comment by jakedot** [comment]
I don't seem to be able to create a new PR based on release. Selecting the release branch and then clicking "New pull request" opens a "Comparing changes" page where I can select my branch jakedot/patch-2 but it then already shows this PR for it, and it doesn't give me the opportunity to create a new one. Does this mean that you maintainers can decide which branch to apply the PR to? https://github.com/cgeo/WhereYouGo/compare/master...jakedot:patch-2?expand=1

**Comment by Lineflyer** [comment]
@jakedot Did not see your "nevermind" early enough and already pushed your branch to a new PR against release.

**Comment by Lineflyer** [comment]
Back one step to try something:
@jakedot Please just click the edit button for the title of this PR and check whether you can there change the base branch to `release`. I was just told, this should be possible.

**Comment by jakedot** [comment]
Yes, that works. Thanks for the hint, didn't see that the base branch becomes editable when doing this.

**Comment by Lineflyer** [comment]
> Didn't see that the base branch becomes editable when doing this.

Looks also new to me.

**Comment by Lineflyer** [comment]
Thanks @jakedot

**Pull request merged**
