### PR TITLE
Improve issue and PR template

### PR DESCRIPTION
**Pull request by Lineflyer**
Align to what we use for c:geo since PR https://github.com/cgeo/cgeo/pull/10356

### CODE REVIEW

**Comment by Lineflyer** [comment]
Does someone one where the the Codacy configuration is done?
I wonder how to suppress these markdown issues (they did not show up on the c:geo PR).

**Comment by SchoolGuy** [comment]
@Lineflyer In case Codacy does not find a configfile (which is not present), you need to log in into Codacy with the right permissions and configure it on the web interface.

**Comment by kumy** [comment]
retest this please

**Comment by kumy** [comment]
retest this please

**Comment by kumy** [comment]
retest this please

**Comment by kumy** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Pull request closed without merging**
