### PR TITLE
migrate to androidx

### PR DESCRIPTION
**Pull request by bekuno**
- migrate support-v4 library to androidx
- update barcode scanner integration for androidx compatibility
  - downgrade to minsdk 14 by using zxing:core 3.3.0
  - additionally needed: im Manifest: <uses-sdk tools:overrideLibrary="com.google.zxing.client.android" />

### CODE REVIEW

**Comment by bekuno** [comment]
@jakedot 
Please check if possible if there is unexpected behavior with the QR-Code scanner.

**Comment by jakedot** [comment]
will check it out tomorrow

**Comment by jakedot** [comment]
looks good to me

**Comment by bekuno** [comment]
Lets wait until the android 8 bugs are solved.

**Pull request merged**
