### PR TITLE
bugfix and compatibility release on legacy branch

### LINKED ISSUE #156: WhereYouGo no longer available for GARMIN Monterra
**Describe the bug:**
Since the last update of WherYouGo the app is no longer available in the Goolge Play Store for GARMIN Monterra devices. 

**Version of WhereYouGo used:**
The Version 0.9.3 was available in the Google Play store for the Monterra device.

**System information (Android version, device model):**
Monterra devices are still running on Ice Cream Sandwich (Android 4.0.4, API level 15).

**Additional context:**
I think this issue might be caused trou the increasing of the minSdkVersion from 15 to 16 in the build.gradle.

### PR DESCRIPTION
**Pull request by bekuno**
- Document the project switch to the cgeo team
- Fixed broken download of cartridges from wherigo.com by switching to https
- Fixed other links by switching to https
- Update the map provider
- Minor code improvements
- Updated the dependencies to compile on current development infrastructure

implements:

- PR #32 (Update about pages) / PR #60 (Update Changelog) / PR #85 (Readme) / maybe more
- PR #9 (partly) (prepare parts for targetSdk 28)
- PR #10 (set dialog close button from "yes" to "close")
- PR #25 (Updated main menu links)
- PR #35 (case statement not finished)
- PR #72 (Map tiles not loading)
- PR #75 (Start Map with OSM)
- PR #167 (make screen turn optional) / #93 (make WhereYouGo work again in Android 8)

fixes: #165
should fix #156

### CODE REVIEW

**Comment by Lineflyer** [comment]
@bekuno 
You need to modify `maxsdk` in the manifest to separate it from the non-legacy version. This will enable us to publish the legacy in parallel to the non-legacy on Google Play.
Google Play will then pick the appropriate version depending on the SDK of the device.

**Comment by bekuno** [comment]
@Lineflyer It is not necessary to define a `maxSdkVersion` here, see
https://developer.android.com/google/play/publishing/multiple-apks#Rules
and https://developer.android.com/google/play/publishing/multiple-apks#SupportedFilters
We need only to fit the rule: the APK with a higher android:minSdkVersion value must have a higher android:versionCode value.
This is true because the legacy version has the old number variant = 46, the release has a date based version number.

**Comment by Lineflyer** [comment]
Thanks for digging this out. I need to read deeper, because the problem here could be that we initially cannot deploy a version with a lower version code. These rules seem to be made for publishing an update which leaves out older SDKs. But now we are live with this kind of update already without having a kept legacy version.

**Comment by bekuno** [comment]
The document (https://developer.android.com/google/play/publishing/multiple-apks#HowItWorks) says only that when using different apk files PGooglePlay needs to distinguish between them. There is no point that new packages need a higher version code than all other apk before.

**Comment by Lineflyer** [comment]
OK, lets find it out once we are ready.
I would still suggest we use the API level as a clear distinguisher as described here: https://developer.android.com/google/play/publishing/multiple-apks#SupportedFilters

**Comment by bekuno** [comment]
The other question is if we need to set the targetSdk number to 28 as defined in https://support.google.com/googleplay/android-developer/answer/113469#targetsdk .
I think yes.
PR is changed for compileSdkVersion, targetSdkVersion, maxSdkVersion

**Comment by bekuno** [comment]
Strange Codacy reports.
Let´s ignore them.

**Comment by Lineflyer** [comment]
I also give up for the codacy markdown issues, the contained fixes seem fine (need to test however). So lets merge and lets see how to test this best.

**Pull request merged**
