### PR TITLE
Apply "Switch to https for cartridge download (#5)" to legacy branch

### PR DESCRIPTION
**Pull request by Lineflyer**
Work on #156 - Make legacy version for Garmin Monterra

### CODE REVIEW

**Comment by Lineflyer** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
from CI:
~~~
mv: cannot stat 'build/outputs/apk/debug/*-debug.apk': No such file or directory
Build step 'Execute shell' marked build as failure
~~~

Ether optimize this on CI or ignore.
The apk is ok.

**Comment by Lineflyer** [comment]
The problem might be, that legacy is on a status before the source was configured to work with our CI.

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
I changed the CI apk rename script to not fail when the file is not in the debug directory.
Instead it prints an info message:
~~~
INFO: apk was not in the debug folder, could not rename
~~~

@kumy Is this ok for you?

**Comment by kumy** [comment]
Sure no problem for me as long it's good for the project :)

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
@Lineflyer 
Instead of changing the legacy branch I changed/optimized the CI rename script.
The output stays in this case unchanged at `whereyougo (PR)-debug.apk`

**Pull request merged**
