### PR TITLE
Hotfix for #329 - Incorrect Language

### PR DESCRIPTION
**Pull request by sk-juroot**
## Description

Fixed few language issues:
- incorrect handling of system default language (usually English is used, when default option selected)
- incorrect language loading order on main settings screen, view falling back to english

## Related issues
- #329 

## Additional context
Since app-level method `CustomActivity.setLocale` was changed, I would recommend to test all activities (CartridgeDetails, Guiding, Main, Satellite). I have opened all of them on API 32 and also API 21 emulator, application worked as expected. 

Also remember to force-restart application after changing language in settings. Users should be notified of reqired restart for applying language changes.

### CODE REVIEW

**Comment by Lineflyer** [comment]
ok to test

@sk-juroot 
Thanks for stepping in. Highly appreciated.

**Comment by Lineflyer** [comment]
ok to test

**Comment by Lineflyer** [comment]
I will merge and test this change.
Regarding the force restart I will open a follow up issue but I don't see this as blocking point for a release as users rarely explicitly change the app language (at least if detection the system default language works again).

**Comment by bekuno** [comment]
@sk-juroot Many thanks for diving in this problem.
Please check, if your patch also works for 2-part languages.
We have currently defined: "pt-rBR","pt-rPT" .

In the old version of MainApplication.java  was this code:
~~~
        // get language
        Configuration config = getBaseContext().getResources().getConfiguration();
        String lang = Preferences.getStringPreference(R.string.pref_KEY_S_LANGUAGE);

        // set language
        if (!lang.equals(getString(R.string.pref_language_default_value))
                && !config.locale.getLanguage().equals(lang)) {
            ArrayList<String> loc = StringToken.parse(lang, "_");
            if (loc.size() == 1) {
                locale = new Locale(lang);
            } else {
                locale = new Locale(loc.get(0), loc.get(1));
            }
            config.locale = locale;
            getBaseContext().getResources().updateConfiguration(config,
                    getBaseContext().getResources().getDisplayMetrics());
        }
~~~

and in XmlSettingsActivity.java

~~~
       } else if (Preferences.comparePreferenceKey(key, R.string.pref_KEY_S_LANGUAGE)) {
            String lang = sharedPreferences.getString(key, "");
            ArrayList<String> loc = StringToken.parse(lang, "_");
            Configuration config = getBaseContext().getResources().getConfiguration();
            java.util.Locale locale;
            if ("default".equals(lang)) {
                locale = java.util.Locale.getDefault();
            } else if (loc.size() == 1) {
                locale = new java.util.Locale(lang);
            } else if (loc.size() == 2) {
                locale = new java.util.Locale(loc.get(0), loc.get(1));
            } else {
                locale = config.locale;
            }
            if (!config.locale.getLanguage().equals(locale.getLanguage())) {
                config.locale = locale;
                getBaseContext().getResources().updateConfiguration(config,
                        getBaseContext().getResources().getDisplayMetrics());
                needRestart = true;
            }
~~~

**Pull request merged**
