### PR TITLE
Hotfix: Android 12 Compatibility

### PR DESCRIPTION
**Pull request by sk-juroot**
## Description
Android API 24 deprecated use of class `LocationManager.GpsStatus`, since GPS is proprietary satellite system. Since Android 12 (API 31) is `GpsStatus` use prohibited and system denies calls for location-related methods when using deprecated `GpsStatus` class.

- Replaced deprecated `GpsStatus` since API 24, implemented `GnssStatus`
- Fixed message asking for permissions even when granted (changed location provider check)

Changed files:
- `geo/location/LocationState.java`
- `geo/location/GpsConnection.java`

## Related issues
- #306

## Additional context
- [GpsStatus class deprecation notice](https://developer.android.com/reference/android/location/GpsStatus)
- [GnssStatus class reference guide](https://developer.android.com/reference/android/location/GnssStatus)

### CODE REVIEW

**Comment by sk-juroot** [comment]
Code contains checks for apropriate API level on phone (API 24 needed for `GnssStatus` support), tests for older Android versions recommended.

**Comment by Lineflyer** [comment]
@sk-juroot 
Thank you very much for stepping into this topic and for the insights provided.
We are very grateful for your contribution.

Could you crosscheck the codacy reports of this PR, whether you can fix these (unless they have been in the code before)?

**Comment by Lineflyer** [comment]
retest this please

**Comment by sk-juroot** [comment]
> @Lineflyer 
> Could you crosscheck the codacy reports of this PR, whether you can fix these (unless they have been in the code before)?

I have commited two changes in accordance with Codacy reports, the last one remaining issue is present due to following the code style introduced before. It can be changed easily, but other developers may be confused later. This project could use a "little" refactor, it will be hard and long task to get this on track with current trends.

**Comment by Lineflyer** [comment]
OK to test

**Comment by Lineflyer** [comment]
@sk-juroot 
> This project could use a "little" refactor, it will be hard and long task to get this on track with current trends.

Indeed...all good.
Meanwhile I got our CI back running again and will merge if test build is green and test behavior on Android 12 and below API 24 afterwards.

Thanks for this hotfix, highly appreciated.

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
@sk-juroot 
Can you rebase this to `master`?
As release is well outdated next release will be from `master` anyway.

**Comment by sk-juroot** [comment]
> @Lineflyer 
> Can you rebase this to master?

Changed target branch of PR, will check if original fix works for `master` later this day. 
Hope that tests will be OK. Fingers crossed for the new release.

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
retest this please

**Comment by Lineflyer** [comment]
@sk-juroot 
I tried it on API31 emulator and its working.

However if I use an API21 up to and including API23 emulator, WhereYouGo crashes on startup. It only works starting with API24. Any idea how to make it work on older API-levels?

```
2021-12-11 10:55:25.013 3285-3285/menion.android.whereyougo E/UncaughtExceptionHandler: uncaughtException main
    java.lang.Exception: java.lang.NoClassDefFoundError: menion.android.whereyougo.geo.location.GpsConnection$MyGnssListener
        at menion.android.whereyougo.utils.Logger.e(Logger.java:50)
        at menion.android.whereyougo.utils.ExceptionHandler.uncaughtException(ExceptionHandler.java:27)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
2021-12-11 10:55:25.015 3285-3285/menion.android.whereyougo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: menion.android.whereyougo, PID: 3285
    java.lang.NoClassDefFoundError: menion.android.whereyougo.geo.location.GpsConnection$MyGnssListener
        at menion.android.whereyougo.geo.location.GpsConnection.<init>(GpsConnection.java:62)
        at menion.android.whereyougo.geo.location.LocationState.setState(LocationState.java:504)
        at menion.android.whereyougo.geo.location.LocationState.setGpsOn(LocationState.java:460)
        at menion.android.whereyougo.gui.extension.activity.CustomMainActivity.onCreate(CustomMainActivity.java:241)
        at menion.android.whereyougo.gui.activity.MainActivity.onCreate(MainActivity.java:342)
        at android.app.Activity.performCreate(Activity.java:5937)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by sk-juroot** [comment]
> @Lineflyer 
> However if I use an API21 up to and including API23 emulator, WhereYouGo crashes on startup. It only works starting with API24. Any idea how to make it work on older API-levels?

Thank you for raising this issue, I have fixed it basically by introducing recommended Codacy code style. Old `GpsStatus` class initialization remains untouched, on phones with APIs <= 24 will code create a new listener for `GnssStatus ` and work with that. Just need to keep in mind, that there are more listeners, than it looks when someone opens `GpsConnection.java` file.

**Review by ztNFny — APPROVED** [review]
looks ok to me code-wise
Style ... well, there's no style in WYG, so no point in starting anything now 😉 Could use some finals and curly brackets here and there, but no point in making this one function nice when the whole project is in need of a rewrite

**Comment by Lineflyer** [comment]
I briefly checked on older API levels and the latest addition to this PR fixed the problem mentioned earlier.
Merging to test in nightlies.

**Comment by lukasMK89** [comment]
Would it be possible to provide an APK installation with a upgrade API level? Until it is officially fixed.
The dysfunction bothers me...

**Comment by Lineflyer** [comment]
I am about to release the update this weekend.
Please keep your installation and upgrade via Google Play once available. Do not uninstall the current version, as this will make file access disfunctional.

Just 1-2 days left.

**Comment by Lineflyer** [comment]
@lukasMK89 
Update. Release train is rolling. Should arrive in some hours or tomorrow via Google Play.

**Pull request merged**
