### PR TITLE
new icon

### LINKED ISSUE #300: new icon?
As you might know I'm working on new map icons for c:geo (https://github.com/cgeo/cgeo/issues/11139) and that of course includes type icons. While at it it'd maybe make sense to also refresh the WYG icon.

The current drafts for WIG-type-icon:
image

The bee one is quite close to the current WYG icon, the others are more similar to the official icon.

Please let me know whether there's interest in this.

### PR DESCRIPTION
**Pull request by ztNFny**
image

fixes #300

### CODE REVIEW

**Review by SchoolGuy — APPROVED** [review]
This is a great step in my eyes and together with the new Settings a huge step forwards!

**Comment by Lineflyer** [comment]
@ztNFny 
While testing other things on WhereYouGo I experienced crashes when running `master` on older API levels (up to including API24). reproducible crash when clicking on map from main screen.

Looks like this:
```
2021-12-11 12:58:01.384 6794-6794/menion.android.whereyougo E/UncaughtExceptionHandler: uncaughtException main
    java.lang.Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{menion.android.whereyougo/menion.android.whereyougo.maps.mapsforge.MapsforgeActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0000
        at menion.android.whereyougo.utils.Logger.e(Logger.java:50)
        at menion.android.whereyougo.utils.ExceptionHandler.uncaughtException(ExceptionHandler.java:27)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
2021-12-11 12:58:01.392 6794-6794/menion.android.whereyougo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: menion.android.whereyougo, PID: 6794
    java.lang.RuntimeException: Unable to start activity ComponentInfo{menion.android.whereyougo/menion.android.whereyougo.maps.mapsforge.MapsforgeActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0000
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0000
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
        at android.content.res.Resources.getDrawable(Resources.java:766)
        at android.content.Context.getDrawable(Context.java:525)
        at com.android.internal.widget.ActionBarView.setIcon(ActionBarView.java:679)
        at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:737)
        at com.android.internal.policy.PhoneWindow.setDefaultIcon(PhoneWindow.java:1737)
        at android.app.Activity.initWindowDecorActionBar(Activity.java:2400)
        at android.app.Activity.setContentView(Activity.java:2415)
        at menion.android.whereyougo.maps.mapsforge.MapsforgeActivity.onCreate(MapsforgeActivity.java:361)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

I tried bisecting it and came down to this PR (If I remove these commits from master the crash is gone).
Any idea?

**Comment by ztNFny** [comment]
Maybe a string reference to the old icon name somewhere that the compiler doesn't pick up?

**Comment by Lineflyer** [comment]
@ztNFny Looks like it. Can you try to debug it? My Java knowledge isn't deep enough for that :(

**Comment by ztNFny** [comment]
```
grep 0x7f0e0000 ./build/intermediates/runtime_symbol_list/debug/R.txt
int mipmap ic_launcher 0x7f0e0000
```
The missing file is mipmap\ic_launcher. Kitkat doesn't support Vector Drawables everywhere yet and it seems Android Studio failed to generate all required legacy drawables when I used its wizard to import the new icon.

**Pull request merged**
