### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by bekuno**
- versions plugin to 0.29.0
- okhttp to 3.12.12
- ndk to 21.3.6528147
- (deactivate version check for android-gif-drawable)
- gradle.enterprise to 3.4.1

### CODE REVIEW

**Comment by bekuno** [comment]
retest this please

**Comment by bekuno** [comment]
retest this please

**Comment by fm-sys** [comment]
Let's do **not** merge this PR but let dependabot do the work for us, which will become active as soon as #252 is merged...

**Comment by Lineflyer** [comment]
We do now have dependabot working for us.

**Pull request closed without merging**
