### PR TITLE
dymanic version code/name

### LINKED ISSUE #43: Improve version codes
Currently the app uses version codes like e.g. 0.9.3.
I suggest to migrate to a similar date based version code and version name as used in c:geo.

Using a date based version code has certain advantages when it comes to different versions like nightlies, RC and production. Additionally we could reuse the related scripts to set the version code/name on our CI.

### PR DESCRIPTION
**Pull request by bekuno**
Fix #43

code is completly reused from cgeo

### CODE REVIEW

**Comment by kumy** [comment]
Does it change the generated apk filenames? If yes, Jenkins jobs need to been modified ;)

**Comment by bekuno** [comment]
@kumy No, only the versionCode and versionCode within build.gradle.

**Comment by bekuno** [comment]
After PR:
~~~
aapt dump badging whereyougo-PR57-2020.03.04-6db1b51-debug.apk
package: name='menion.android.whereyougo' versionCode='20200304' versionName='2020.03.04-d66a51b developer build' compileSdkVersion='28' compileSdkVersionCodename='9'
...
~~~

**Comment by Lineflyer** [comment]
Great, lets test that.

**Pull request merged**
